title: Experience
icon: fa fa-briefcase
jobs:
  - name: Beta District
    position: Software Engineer
    period: 2017 - 2020
    desc: A job description is a document that describes the general tasks, or other related, and responsibilities of a position. It may specify the functionary to whom the position reports.
  - name: Madkom SA
    position: PHP Developer
    period: 2014 - 2017
    desc: A job description is a document that describes the general tasks, or other related, and responsibilities of a position. It may specify the functionary to whom the position reports.
